language: node_js
node_js: '6.11.0'
cache: yarn
before_script:
  - git config --global user.name "Andy Chen"
  - git config --global user.email "shinningstar1001@gmail.com"
  - git clone --branch gh-pages https://${GH_REF} dist

script:
  - npm test

after_success:
  - npm run build
  - git add --all .
  - git commit --message "Automatically update from travis-ci"
  - git push --quiet "https://${GH_TOKEN}@${GH_REF}" gh-pages:gh-pages

# Note: you should set Environment Variables here or 'Settings' on travis-ci.org
env:
  global:
    - GH_REF: github.com/Asing1001/badmintonmap.vue.git
    # - GH_TOKEN: 'Your GitHub Personal access tokens, via https://github.com/settings/tokens'
