dist: trusty
sudo: false
addons:
  chrome: stable
language: node_js
node_js: '6.11.0'
cache: yarn
before_script:
  - jdk_switcher use oraclejdk8
  - git config --global user.name "Andy Chen"
  - git config --global user.email "shinningstar1001@gmail.com"
  - git clone --branch package.${TRAVIS_BRANCH} https://${GH_REF} ${PACKAGE_FOLDER}

script:
  - npm run build
  - npm test

after_success:
  - cd ${PACKAGE_FOLDER}
  - rm -rf *
  - cp -r ../dist/* .
  - cp -r ../server/* .
  - find .
  - git add --all .
  - git commit --message "${TRAVIS_COMMIT_MESSAGE} [ci skip]"
  - git push --force "https://${GH_TOKEN}@${GH_REF}" package.${TRAVIS_BRANCH}:package.${TRAVIS_BRANCH}

env:
  global:
    - GH_REF: github.com/Asing1001/badmintonmap.vue.git
    - PACKAGE_FOLDER: mypackages
    - API_HOST: https://badmap-api.mvrater.com
